### ISSUE TITLE
How to output the analogRead() value to the display

### ISSUE THREAD

**Issue by bogdanr** [nickgammon/MAX7219_Dot_Matrix#2]
I clearly understand from the examples how to print a predefined text but I don't get how to actually display a dynamic value.

This bit of code:

```
adc = analogRead(A0);
Serial.println(analogRead(A0));
display.sendString(adc);
```
Produces this error:

    invalid conversion from 'int' to 'const char*' [-fpermissive]

**Comment by nickgammon** [comment]
The "sendString" function expects a string and isn't designed to send things like ints. However you can "sprintf" or otherwise convert an int into a string and then print that. For example:

```c++
  char buf [10];
  int adc = analogRead (A0);
  itoa (adc, buf, 10);    // convert to string, base 10
  display.sendString (buf);
```

or:

```c++
  char buf [10];
  int adc = analogRead (A0);
  sprintf (buf, "%i", adc);
  display.sendString (buf);
```

The buffer just needs to be long enough to hold the number and a terminating 0x00 character. 10 bytes might be overkill, probably 7 would be enough.

If you use sprintf you can add text as well, eg.


```c++
  char buf [20];
  int adc = analogRead (A0);
  sprintf (buf, "Reading: %i", adc);
  display.sendString (buf);
```

**Comment by bogdanr** [comment]
Works like a charm!
Thanks and happy holidays if Easter is a thing for you!
